# Numpy Tutorial
This notebook was originally prepared as part of the "Intro to deep learning" course by Moeen Tayebi, in August of 2020. It has been been used as a stand-alone matrix/numpy introduction as well.

To get the most out of this tutorial, it is recommended that the reader be relatively comfortable with using for loops and lists (no matter the programming language).

## Part Zero: Introduction to Google Colab

Google Colab is a service that can be used to run python codes on a remote system without needing to have any python interpreter or even editor on your own system. It's basic account is free but in order to be able to use it for longer periods or have more speed when using GPUs or TPUs, you can upgrade to a premium account.

There are three runtime types available: CPU, GPU, and TPU. Using GPUs or TPUs is not recommended unless you really need to use one. For running python codes you just have to type the codes in the boxes that accept code and run them by either clicking on the play button that appears on their top left corner or by pressing Shift + Enter while the cursor is in the box(clicking inside the box might be necessary).

Google colab has the packages that come with the regular python installation(including pip) and also includes some other useful packages(such as Numpy). For installing new packages, do as you do in your own system and type whatever commands you have to type in the command line(e.g. `pip install tensorflow`), preceeded by an exclamation mark. The exclamation mark at the beginning of the command makes the colab interpreter understand that this command is not a python command, but a system command, and so has to be handled accordingly. For example, in order to install some package named "IDKPackage" that is installable by pip, you just have to type `!pip install IDKPackage`.

## Part One: Numpy Basics

First, the two necessary libraries are imported.

In [1]:
import numpy as np
print(np.__version__)
from time import time

1.18.5


Then we shall explore some simple numpy operations.

Starting with vectors(one dimensional lists of numbers).

numpy function: `numpy.arange()`

In [2]:
# Making simple vectors(numpy ndarray)
vec1 = np.arange(10)
print(type(vec1))
print(vec1)
vec2 = np.arange(3, 10)
print(vec2)
vec3 = np.arange(3, 10, 2)
print(vec3)

<class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9]
[3 4 5 6 7 8 9]
[3 5 7 9]


Then we'll see how numpy arrays are created from lists:

numpy function: `numpy.array()`

In [3]:
# Making a vector from a python list
vec_as_list4 = [2, 5, 6, 7]
vec4 = np.array(vec_as_list4)
print(vec4)

[2 5 6 7]


Adding vectors with numpy and comparing the result with the addition of two lists:

numpy function: `numpy.add()`

In [4]:
# Adding two numpy vectors
vec5 = vec3 + vec4
print(vec5)
vec6 = np.add(vec3, vec4)
print(vec6)

# Adding(!) two python lists
vec_as_list3 = [3, 5, 7, 9]
vec_as_list5 = vec_as_list4 + vec_as_list3
print(vec_as_list5)

[ 5 10 13 16]
[ 5 10 13 16]
[2, 5, 6, 7, 3, 5, 7, 9]


Adding a scalar to numpy vectors and lists will help us observe the broadcasting property of numpy and appreciate it!

In [5]:
# Adding a scalar value to a numpy vector(ndarray) ==> Broadcasting
vec7 = np.add(vec1, 1)
print(vec7)

# Trying to add a scalar value to a list
try:
  vec_as_list6 = vec_as_list3 + 1
  print(vec_as_list6)
except TypeError:
  print("Error: Can't add a scalar value(here, an int) to a list!")

[ 1  2  3  4  5  6  7  8  9 10]
Error: Can't add a scalar value(here, an int) to a list!


Moving on to matrices!

The first matrix is created by reshaping a 1x9 vector into a 3x3 matrix!

The second matrix is created from a 2-d list.

It can be seen that the matrices and vectors created by numpy are of the same type(ndarray) and numpy handles them in a similar manner.

numpy function: `np.ndarray.reshape()`

In [6]:
# Making a matrix by reshaping a vector
mat1 = np.arange(9.0).reshape((3, 3))
print(mat1)
print(type(mat1))
# Making a matrix from a list
two_dimensional_list1 = [[1, 2, 3],
                         [4, 5 ,6],
                         [7, 8, 9]]
mat2 = np.array(two_dimensional_list1)
print(mat2)

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Next, we'll see how we can transform a numpy array(matrix or vector) into a python list.

numpy function: `np.ndarray.tolist()`

In [7]:
# Making a 2-d list from a numpy matrix
two_dimensional_list2 = mat1.tolist()
print(two_dimensional_list2)

[[0.0, 1.0, 2.0], [3.0, 4.0, 5.0], [6.0, 7.0, 8.0]]


Next we'll see some basic matrices:

The first matrix is a 1x3 matrix(= a vector of size 3) of zeros.

The second matrix is a 3x3 matrix of ones.

The third matrix is the $I_{3}$ or as we know it, the identity matrix of size 3.

The forth matrix is a 3x5 matrix that all of its elements are set to be 77.

The last matrix is a 4x2 matrix whose elements are not initialized. 

numpy functions: `np.zeros(), np.ones(), np.identity(), np.full(), np.empty()`

In [8]:
# Some useful and famous matrices
zeros_mat = np.zeros(3)
print(zeros_mat)
ones_mat = np.ones((3,3))
print(ones_mat)
identity_mat = np.identity(3)
print(identity_mat)
arbit_mat = np.full((3,5), 77)
print(arbit_mat)
empty_mat = np.empty((4,2))
print(empty_mat)

[0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[77 77 77 77 77]
 [77 77 77 77 77]
 [77 77 77 77 77]]
[[1. 2.]
 [3. 4.]
 [5. 6.]
 [7. 8.]]


Next, Adding two matrices together and comparing the same operation on 2-d lists.

In [9]:
# Adding two matrices together
mat3 = np.add(mat1, mat2)
print(mat3)
mat4 = np.add(mat1, ones_mat)
print(mat4)

# Adding two 2-d lists together
two_dimensional_list3 = two_dimensional_list1 + two_dimensional_list2
print(two_dimensional_list3)

[[ 1.  3.  5.]
 [ 7.  9. 11.]
 [13. 15. 17.]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[1, 2, 3], [4, 5, 6], [7, 8, 9], [0.0, 1.0, 2.0], [3.0, 4.0, 5.0], [6.0, 7.0, 8.0]]


Then, a scalar and a vector will be added to a numpy matrix and the result will be compared with the result of the same operation on a 2-d list.

Here Broadcasting can be seen in two forms:

First, in adding a single scalar to a matrix which is the same as adding a scalar to a vector.

$
\begin{bmatrix}
1\\
2\\
3\\
\end{bmatrix} + 1 = \begin{bmatrix}
1\\
2\\
3\\
\end{bmatrix} + \begin{bmatrix}
1\\
1\\
1\\
\end{bmatrix} = \begin{bmatrix}
2\\
3\\
4\\
\end{bmatrix}
$


The second form of broadcasting looks new but it's nothing surprising. This happens when a vector is added to a matrix.

$
\begin{bmatrix}
0 & 1 & 2\\
3 & 4 & 5\\
6 & 7 & 8\\
\end{bmatrix} + \begin{bmatrix}
0 & 1 & 2\\
\end{bmatrix} = \begin{bmatrix}
0 & 1 & 2\\
3 & 4 & 5\\
6 & 7 & 8\\
\end{bmatrix} + \begin{bmatrix}
0 & 1 & 2\\
0 & 1 & 2\\
0 & 1 & 2\\
\end{bmatrix} = \begin{bmatrix}
0 & 2 & 4\\
3 & 5 & 7\\
6 & 8 & 10\\
\end{bmatrix}
$

Run the cell below to observe this better.


From the [numpy documentation](https://https://numpy.org/doc/stable/reference/generated/numpy.add.html): The arrays to be added. If x1.shape != x2.shape, they must be broadcastable to a common shape (which becomes the shape of the output).

In [10]:
# Adding a scalar value to a numpy matrix
mat5 = np.add(mat1, 1)
print(mat5)

# Adding a vector to a numpy matrix  ==> Broadcasting
new_vec = np.arange(3)
mat6 = np.add(mat1, new_vec)
print(mat6)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[ 0.  2.  4.]
 [ 3.  5.  7.]
 [ 6.  8. 10.]]


Broadcasting can be seen in multiplying of a matrix in a scalar as well.

But multiplying a matrix in a vector, doesn't need broadcasting to result in a valid and correct output. I'm not gonna discuss the mathematics for that here but it is similar to the multiplication of matrices.

The codes and functions for the multiplication operations won't be discussed in this tutorial.

It must be obvious by now that performing these operations(adding a scalar or a vector to a matrix) on python lists will either result in an error or an incorrect output.

Next we will see transpose, inverse and matrix multiplication functions.

The theories and definitions for these operations have been discussed in the lecture.

Consider the matrix $A = \begin{bmatrix}
0 & 2 & 1\\
3 & 4 & 5\\
6 & 7 & 8\\
\end{bmatrix}$

Transpose:
$
A^{T} = \begin{bmatrix}
0 & 3 & 6\\
2 & 4 & 7\\
1 & 5 & 8\\
\end{bmatrix}
$

Inverse:
$
A^{-1} = \begin{bmatrix}
-0.33 & -1.00 & 0.66\\
0.66 & -0.66 & 0.33\\
-0.33 & 1.33 & -0.66\\
\end{bmatrix}
$

Matrix multiplication: $A \times A^{-1} = 
\begin{bmatrix}
1 & 0 & 0\\
0 & 1 & 0\\
0 & 0 & 1\\
\end{bmatrix}
$

numpy functions: `np.transpose(), np.linalg.inv(), np.dot()`


In [11]:
A = np.array([[0, 2, 1],
              [3, 4, 5],
              [6, 7, 8]])

A_T = np.transpose(A)
print("The transpose of the matrix:")
print(A_T)

A_inv = np.linalg.inv(A)
print("The inverse of the matrix:")
print(A_inv)

Multiplication_result = np.dot(A_inv, A)
print("The multiplication of the matrix and its inverse:")
print(Multiplication_result)

The transpose of the matrix:
[[0 3 6]
 [2 4 7]
 [1 5 8]]
The inverse of the matrix:
[[-0.33333333 -1.          0.66666667]
 [ 0.66666667 -0.66666667  0.33333333]
 [-0.33333333  1.33333333 -0.66666667]]
The multiplication of the matrix and its inverse:
[[ 1.00000000e+00 -5.55111512e-16  0.00000000e+00]
 [-1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [ 2.22044605e-16 -3.33066907e-16  1.00000000e+00]]


Two important points:

1. The order in which you give the inputs to the `np.dot()` function is very important. Its importance is not very visible in this example because if we had used `np.dot(A, A_inv)` instead of `np.dot(A_inv, A)`, the result would have been the same(the identity matrix). This is because regardless of the side of a matrix you multiply its inverse from, you will always get the identity of the corresponding dimension. But in the general cases where you want to multiply two random matrices, putting them in the wrong order can even lead to errors(due to having mismatched sizes).

2. The values in the last matrix that end with `...e-16` can be thought of as $0$. The exact meaning of that phrase is out of the scope of this tutorial but it means that the values are very very small, so they are very close to $0$.

## Part two: Matrix multiplication speed!

As it was mentioned in the presentation the process of multiplying a matrix in another matrix involves a lot of small multiplication and addition operations between the elements(single numbers) of the matrices. Central Processing Units(CPUs) have a large number of units that can perfom simple mathematical operations like multiplying two single numbers together in parallel. It turns out that Graphical Processing Units(GPUs) have many more processing units than the CPUs but unlike the units in a CPU, GPU units are just specialized in performing a limited range of operations (such as the simple mathematical operations that are performed in a matrix multiplication). This means that by utilizing the ability of the CPU or GPU to process different small multiplications simultaneously and in parallel, a matrix multiplication can be done with a very high speed. On the other hand, if you don't utilize this ability of a CPU/GPU and just implement the matrix multiplication with some nested for loops in your code, you can see that it takes a much longer time to perform the same operation.

In this part of the tutorial, we are going to compare the speed of a matrix multiplication with two different implementations:

1.   Using for loops to iterate over elements
2.   Using the built-in numpy functions(such as np.dot)

First two small(2x2) matrices will be investigated to see how long multiplying them will take with each of the implementations. Then we will do the same thing with two larger matrices(one 22x20 and one 20x18).

It is worth noting that accessing the element of a numpy ndarray(matrix) that is at the i-th row and the j-th column, can be done using the `[i,j]` format; A two dimensional python list doesn't support this and should be accessed using `[i][j]`.

Run the cells below to see how long each of these implementations take to come up with the answer and compare the results between the implementations and the two different sizes!



In [12]:
# small matrix as a list No. 1
Smat1 = [[1, 2],
         [3, 4]]
# small matrix as a list No. 2
Smat2 = [[2, 3],
         [4, 5]]

#Smat1 = Mat1.tolist()
#Smat2 = Mat2.tolist()

# Getting the dimensions of the two matrices
m_1 = len(Smat1)
n_1 = len(Smat1[0])
m_2 = len(Smat2)
n_2 = len(Smat2[0])
# What is the condition for the multiplication of these two matrices(mat1 * mat2) to be valid?

result = [[None for _ in range(n_2)] for _ in range(m_1)]  # No need to understand this. This just makes an empty 2-D list to store the results after computing them one by one.
start = time()
for i in range(m_1):
  for j in range(n_2):
    temp = 0
    for k in range(m_2):
      temp += (Smat1[i][k] * Smat2[k][j])
    result[i][j] = temp
finish = time()

print(f"The small multiplication with for loops took {(finish - start) * 1000} ms")
print("The result is:")
print(result)

The small multiplication with for loops took 0.9934902191162109 ms
The result is:
[[10, 13], [22, 29]]


In [13]:
# small matrix as a numpy array No. 1
Mat1 = np.array(Smat1)
# small matrix as a numpy array No. 2
Mat2 = np.array(Smat2)
start = time()
result_np = np.dot(Mat1, Mat2)
finish = time()
print(f"The small multiplication with numpy took {(finish - start) * 1000} ms")
print("The result is:")
print(result_np)

The small multiplication with numpy took 0.0 ms
The result is:
[[10 13]
 [22 29]]


In [14]:
# Large matrix as a numpy array No. 3
Mat3 = np.empty((100,120))
# Large matrix as a numpy array No. 4
Mat4 = np.empty((120,140))
start = time()
result_np = np.dot(Mat3, Mat4)
finish = time()
print(f"The large multiplication with numpy took {(finish - start) * 1000} ms")
print("The result is:")
print(result_np)

The large multiplication with numpy took 187.6518726348877 ms
The result is:
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [15]:
Lmat3 = Mat3.tolist()
Lmat4 = Mat4.tolist()

# What will be the dimension of Lmat3 * Lmat4?
m_1 = len(Lmat3)
n_1 = len(Lmat3[0])
m_2 = len(Lmat4)
n_2 = len(Lmat4[0])
result = [[None for _ in range(n_2)] for _ in range(m_1)]
start = time()
for i in range(m_1):
  for j in range(n_2):
    temp = 0
    for k in range(m_2):
      temp += (Lmat3[i][k] * Lmat4[k][j])
    result[i][j] = temp
finish = time()
print(f"The large multiplication with for loops took {(finish - start) * 1000} ms")
print("The result is:")
print(result)

The large multiplication with for loops took 920.781135559082 ms
The result is:
[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0

As you can see from the results of the above cells, you can see that for multiplying relatively small matrices, there is almost no difference between the execution speed of a matrix maultiplication implemented manually using nested `for` loops, and a matrix multiplication implemented using the the numpy built-in functions.

But for the case of relatively large matrices, the difference in speed is obvious in the two implementations.

It's worth noting that a regular matrix in a deep learning model is much larger than the matrices used in our example for "large matrices". But using two matrices with dimensions of about 20x20 suffices for serving the purpose of this tutorial.

## Part three: Solving the simplest matrix equation!

In the third and last part of this tutorial, we will see how a simple matrix equation is solved using numpy arrays and built-in functions.

$A \times x = b$  => $x = A^{-1} \times b$

Where $ A = 
\begin{bmatrix}
3 & 7 \\
2 & 5 \\ 
\end{bmatrix}$
and $ b =
\begin{bmatrix}
2 \\
7 \\ 
\end{bmatrix}$.

The mathematical material related to this problem can be found in the PDF of the lecture which has been uploaded as well.

In [16]:
A = np.array([[3, 7], [2, 5]])
b = np.array([2, 7])

# This is the function that outputs the inverse of a matrix.
A_inv = np.linalg.inv(A)

x = np.dot(A_inv, b)

print(x)

[-39.  17.]


"Psuedo inverse" was introduced in the lecture as a bonus material. We won't dive into the mathematics behind it but using pseudo inverse, one can obtain something that functions similar to the inverse of a matrix, even if the matrix is not in a square form and therefore does not have an inverse. There are multiple formulas for obtaining the pseudo inverse of a matrix.

One of the formulas for calculating the pseudo invese of a matrix is as follows.

For a matrix $A$ whose columns are linearly independent, the left pseudo invese is:

$ A^{+} = (A^{T} \times A)^{-1} \times A^{T}$

For a matrix $A$ whose rows are linearly independent, the right pseudo invese is:

$ A^{+} = A^{T} \times (A \times A^{T})^{-1}$

This is just for those who are interested and the derivation of this formula will not be discussed here.

In the cell below, you can see the pseudo inverse of a non-square matirx.

In [17]:
C = np.array([[1, 1, 1, 1], [5, 7, 7, 9]])
print(C)
try:
  C_inv = np.linalg.inv(C)
  print(C_inv)
except np.linalg.LinAlgError:
  print("Error: The matrix is not invertible!")

C_pinv = np.linalg.pinv(C)
print("The pseudo inverse matrix:")
print(C_pinv)

result = np.dot(C, C_pinv)
print("The result of the pseudo inverse of the matrix multiplied in the matrix itself:")
print(result)

[[1 1 1 1]
 [5 7 7 9]]
Error: The matrix is not invertible!
The pseudo inverse matrix:
[[ 2.00000000e+00 -2.50000000e-01]
 [ 2.50000000e-01  4.16333634e-17]
 [ 2.50000000e-01  4.85722573e-17]
 [-1.50000000e+00  2.50000000e-01]]
The result of the pseudo inverse of the matrix multiplied in the matrix itself:
[[ 1.00000000e+00  1.66533454e-16]
 [-5.32907052e-15  1.00000000e+00]]
